version: '2'

services:
  nginx:
    image: nginx:1.19.8
    ports:
      - "80:80"
    volumes: 
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/image.jpg:/usr/share/nginx/html/images/image.jpg
    